slogan: 爱科技、爱生活、爱折腾......

menu:
  - title: 归档
    url: archives
    intro: 所有归档的文章.
    icon: fa fa-archive
  - title: 类别
    url: categories
    intro: 所有分类.
    icon: fa fa-folder
  - title: 标签
    url: tags
    intro: 所有标签.
    icon: fa fa-tags
  - title: 关于
    url: about
    intro: 关于我.
    icon: fa fa-user

links:
  - title: RSS
    url: atom.xml
    intro: RSS
    icon: fa fa-rss-square
  # - title: My Github
  #  url: http://www.github.com/newroc
  #  intro: My Github account.
  #  icon: fa fa-github
widgets:
- search
- category
- tagcloud
- recent_posts  
- links
#- weibo

rss: 
fancybox: true
favicon: favicon.png
google_analytics: 
baidu_tongji: true


